# Generated by Django 3.2.4 on 2021-06-17 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmapp', '0002_auto_20210616_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestone',
            name='deadline_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha planificación'),
        ),
    ]
